array 09
hieuneko/JavaBasic pull request #23
Opened 2023-02-07 08:47 UTC by hieuneko

pass test

2023-02-07 10:27 UTC, hukacode requested changes

2023-02-07 10:27 UTC, hukacode commented on src/main/java/com/phamhieu/exercise/basic/array/Array09.java
> +        for (int i = 2; i < n; i++) {
Số nguyên tố thì chỉ cần check tới  `i <= n/2` là được

2023-02-07 10:29 UTC, hieuneko commented on src/main/java/com/phamhieu/exercise/basic/array/Array09.java
> +        for (int i = 2; i < n; i++) {
done

2023-02-07 16:11 UTC, voquanghoa commented on src/main/java/com/phamhieu/exercise/basic/array/Array09.java
> +        for (int i = 2; i < n; i++) {
Còn nhanh hơn nữa nếu đổi biểu thức thành `i * i < n`

2023-02-08 02:31 UTC, hieuneko commented on src/main/java/com/phamhieu/exercise/basic/array/Array09.java
> +        for (int i = 2; i < n; i++) {
done

2023-02-08 03:03 UTC, merged