String05
hieuneko/JavaBasic pull request #34
Opened 2023-02-08 08:26 UTC by hieuneko

pass test

2023-02-08 15:01 UTC, nguyenvanman requested changes

2023-02-08 15:01 UTC, nguyenvanman commented on src/main/java/com/phamhieu/exercise/basic/string/String05.java
> +        int sumInEven = 0;
Không cần dùng đến 2 biến sum

2023-02-09 02:07 UTC, hieuneko commented on src/main/java/com/phamhieu/exercise/basic/string/String05.java
> +        int sumInEven = 0;
done

2023-02-10 16:14 UTC, voquanghoa commented on src/main/java/com/phamhieu/exercise/basic/string/String05.java
> +            int temp = Integer.parseInt(String.valueOf(input.charAt(i)));
```suggestion
            int temp = input.charAt(i) - '0';
```

2023-02-10 16:15 UTC, voquanghoa commented on src/main/java/com/phamhieu/exercise/basic/string/String05.java
> +            }
```suggestion
            if (i % 2 == 1) {
                sum += 3 * temp;
            } else {
                sum += temp;
            }
```

2023-02-14 02:42 UTC, hieuneko commented on src/main/java/com/phamhieu/exercise/basic/string/String05.java
> +            int temp = Integer.parseInt(String.valueOf(input.charAt(i)));
done

2023-02-14 02:42 UTC, hieuneko commented on src/main/java/com/phamhieu/exercise/basic/string/String05.java
> +            }
done

2023-02-14 03:02 UTC, merged