string 07
hieuneko/JavaBasic pull request #36
Opened 2023-02-08 10:19 UTC by hieuneko

pass test

2023-02-08 14:37 UTC, nguyenvanman requested changes

2023-02-08 14:37 UTC, nguyenvanman commented on src/main/java/com/phamhieu/exercise/basic/string/String07.java
> +            for (int j = 0; j < containString.length(); j++) {
Dùng substring

2023-02-09 02:03 UTC, hieuneko commented on src/main/java/com/phamhieu/exercise/basic/string/String07.java
> +            for (int j = 0; j < containString.length(); j++) {
done

2023-02-10 16:12 UTC, voquanghoa commented on src/main/java/com/phamhieu/exercise/basic/string/String07.java
> +    public boolean checkContainString(final String input, final String subString) {
Phải trả về index là kết quả tìm thấy chứ

2023-02-14 02:36 UTC, hieuneko commented on src/main/java/com/phamhieu/exercise/basic/string/String07.java
> +    public boolean checkContainString(final String input, final String subString) {
done

2023-02-14 06:35 UTC, voquanghoa commented on src/main/java/com/phamhieu/exercise/basic/string/String07.java
> +
Không có cái này thì có sao không

2023-02-14 06:35 UTC, voquanghoa commented on src/main/java/com/phamhieu/exercise/basic/string/String07.java
> +            }
Tách đoạn này ra, vcl

2023-02-16 03:34 UTC, voquanghoa commented on src/main/java/com/phamhieu/exercise/basic/string/String07.java
> +    private static boolean isStringFoundAt(String input, String subString, int index) {
Thêm final

2023-02-16 03:34 UTC, voquanghoa approved these changes

2023-02-16 03:40 UTC, hieuneko commented on src/main/java/com/phamhieu/exercise/basic/string/String07.java
> +    private static boolean isStringFoundAt(String input, String subString, int index) {
done

2023-02-16 03:41 UTC, merged